const beverages = [{
        id: 1,
        name: "Masala Chai",
        price: 80,
        description: "Traditional Indian spiced tea brewed with milk and aromatic spices.",
        image: "masala-chai.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 2,
        name: "Cold Coffee",
        price: 150,
        description: "Chilled and creamy coffee blended with milk and ice.",
        image: "cold-coffee.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 3,
        name: "Fresh Lime Soda",
        price: 120,
        description: "Refreshing lime soda available in sweet or salty flavors.",
        image: "fresh-lime-soda.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 4,
        name: "Mango Lassi",
        price: 180,
        description: "Thick and creamy yogurt-based mango drink with a hint of cardamom.",
        image: "mango-lassi.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 5,
        name: "Filter Coffee",
        price: 100,
        description: "Authentic South Indian filter coffee served hot and frothy.",
        image: "filter-coffee.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 6,
        name: "Green Tea",
        price: 90,
        description: "Healthy and refreshing green tea with antioxidants.",
        image: "green-tea.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 7,
        name: "Orange Juice",
        price: 140,
        description: "Freshly squeezed orange juice packed with Vitamin C.",
        image: "orange-juice.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 8,
        name: "Strawberry Milkshake",
        price: 160,
        description: "Creamy milkshake blended with fresh strawberries and ice cream.",
        image: "strawberry-milkshake.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 9,
        name: "Pina Colada (Non-Alcoholic)",
        price: 200,
        description: "A tropical blend of pineapple juice and coconut cream.",
        image: "pina-colada.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 10,
        name: "Coconut Water",
        price: 130,
        description: "Natural and refreshing coconut water, rich in electrolytes.",
        image: "coconut-water.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 11,
        name: "Lemon Iced Tea",
        price: 150,
        description: "Chilled black tea infused with lemon and served with ice.",
        image: "lemon-iced-tea.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 12,
        name: "Blue Lagoon Mocktail",
        price: 220,
        description: "A fizzy and refreshing blue-colored mocktail with a citrusy twist.",
        image: "blue-lagoon.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 13,
        name: "Watermelon Juice",
        price: 140,
        description: "Freshly blended watermelon juice, naturally sweet and hydrating.",
        image: "watermelon-juice.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 14,
        name: "Chocolate Shake",
        price: 170,
        description: "Thick and creamy milkshake made with rich chocolate syrup.",
        image: "chocolate-shake.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 15,
        name: "Apple Cider",
        price: 190,
        description: "Refreshing apple-flavored drink with a hint of cinnamon.",
        image: "apple-cider.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 16,
        name: "Virgin Mojito",
        price: 210,
        description: "A cooling blend of mint, lime, and soda with a refreshing taste.",
        image: "virgin-mojito.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 17,
        name: "Kiwi Cooler",
        price: 230,
        description: "A tropical kiwi-based mocktail with a refreshing taste.",
        image: "kiwi-cooler.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 18,
        name: "Badam Milk",
        price: 180,
        description: "Warm milk infused with almonds, saffron, and cardamom.",
        image: "badam-milk.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 19,
        name: "Vanilla Frappe",
        price: 190,
        description: "Iced vanilla coffee blended with milk and whipped cream.",
        image: "vanilla-frappe.jpg",
        button: true,
        quantity: 1,
    },
    {
        id: 20,
        name: "Rose Sherbet",
        price: 160,
        description: "Chilled rose-flavored drink with a refreshing floral taste.",
        image: "rose-sherbet.jpg",
        button: true,
        quantity: 1,
    }
];

export default beverages;