const nonVegMainCourse = [
    {
      id: 1,
      name: "Butter Chicken",
      price: 420,
      description: "Tender chicken cooked in a rich, creamy tomato-based gravy.",
      image: "./NonVegMaincourse/1.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 2,
      name: "Chicken Curry",
      price: 380,
      description: "Classic Indian-style chicken cooked in a spicy, flavorful curry.",
      image: "./NonVegMaincourse/2.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 3,
      name: "Mutton Rogan Josh",
      price: 450,
      description: "Traditional Kashmiri mutton curry with rich spices and yogurt.",
      image: "./NonVegMaincourse/3.jpeg",
      button: true,
      quantity: 1,
    },
    {
      id: 4,
      name: "Prawn Masala",
      price: 480,
      description: "Juicy prawns cooked in a thick and spicy onion-tomato masala.",
      image: "./NonVegMaincourse/4.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 5,
      name: "Fish Curry",
      price: 400,
      description: "Fresh fish simmered in a tangy and mildly spiced curry.",
      image: "./NonVegMaincourse/5.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 6,
      name: "Egg Curry",
      price: 320,
      description: "Boiled eggs cooked in a rich, spicy tomato and onion-based gravy.",
      image: "./NonVegMaincourse/6.jpeg",
      button: true,
      quantity: 1,
    },
    {
      id: 7,
      name: "Chicken Chettinad",
      price: 430,
      description: "South Indian-style spicy chicken curry with coconut and black pepper.",
      image: "./NonVegMaincourse/7.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 8,
      name: "Kadai Chicken",
      price: 410,
      description: "Chicken stir-fried with capsicum and spices in a thick masala gravy.",
      image: "./NonVegMaincourse/8.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 9,
      name: "Mutton Keema",
      price: 460,
      description: "Minced mutton cooked with onions, tomatoes, and aromatic spices.",
      image: "./NonVegMaincourse/9.jpeg",
      button: true,
      quantity: 1,
    },
    {
      id: 10,
      name: "Tandoori Chicken Gravy",
      price: 450,
      description: "Smoky tandoori chicken pieces cooked in a rich, flavorful gravy.",
      image: "./NonVegMaincourse/10.jpeg",
      button: true,
      quantity: 1,
    },
    {
      id: 11,
      name: "Chicken Lababdar",
      price: 430,
      description: "Boneless chicken cooked in a creamy, slightly tangy tomato-based gravy.",
      image: "./NonVegMaincourse/11.jpeg",
      button: true,
      quantity: 1,
    },
    {
      id: 12,
      name: "Goan Fish Curry",
      price: 460,
      description: "Goan-style coconut and tamarind-based fish curry.",
      image: "./NonVegMaincourse/12.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 13,
      name: "Andhra Chicken Curry",
      price: 420,
      description: "Spicy and tangy South Indian-style chicken curry.",
      image: "./NonVegMaincourse/13.jpeg",
      button: true,
      quantity: 1,
    },
    {
      id: 14,
      name: "Bengali Mutton Curry",
      price: 470,
      description: "Traditional Bengali-style slow-cooked mutton curry with mustard oil.",
      image: "./NonVegMaincourse/14.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 15,
      name: "Prawn Malai Curry",
      price: 500,
      description: "Creamy Bengali-style prawn curry cooked with coconut milk.",
      image: "./NonVegMaincourse/15.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 16,
      name: "Mutton Handi",
      price: 490,
      description: "Slow-cooked mutton curry made in a traditional clay pot.",
      image: "./NonVegMaincourse/16.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 17,
      name: "Egg Masala",
      price: 350,
      description: "Boiled eggs simmered in a spicy onion-tomato masala.",
      image: "./NonVegMaincourse/17.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 18,
      name: "Mughlai Chicken",
      price: 440,
      description: "Creamy and flavorful chicken curry with rich Mughlai spices.",
      image: "./NonVegMaincourse/18.jpeg",
      button: true,
      quantity: 1,
    },
    {
      id: 19,
      name: "Nihari Mutton",
      price: 510,
      description: "Slow-cooked mutton stew with aromatic spices, best served with naan.",
      image: "./NonVegMaincourse/19.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 20,
      name: "Chicken Vindaloo",
      price: 420,
      description: "Goan-style chicken curry cooked with vinegar and bold spices.",
      image: "./NonVegMaincourse/20.jpg",
      button: true,
      quantity: 1,
    }
  ];
  
  export default nonVegMainCourse;
  