const nonVegStarters = [{
    id: 1,
    name: "Chicken Tandoori",
    price: 320,
    description: "Char-grilled chicken marinated with yogurt and Indian spices.",
    image: "./nonvegstarters/1.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 2,
    name: "Chicken 65",
    price: 280,
    description: "Spicy, deep-fried chicken pieces tossed with curry leaves and chilies.",
    image: "./nonvegstarters/2.jpeg",
    button: true,
    quantity: 1,
  },
  {
    id: 3,
    name: "Mutton Seekh Kebab",
    price: 350,
    description: "Juicy minced mutton kebabs grilled with aromatic spices.",
    image: "./nonvegstarters/3.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 4,
    name: "Prawn Tempura",
    price: 380,
    description: "Crispy battered prawns served with a tangy dipping sauce.",
    image: "./nonvegstarters/4.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 5,
    name: "Fish Amritsari",
    price: 330,
    description: "Crispy fried fish marinated in tangy spices and gram flour.",
    image: "./nonvegstarters/5.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 6,
    name: "Mutton Galouti Kebab",
    price: 370,
    description: "Soft, melt-in-mouth mutton kebabs served with saffron paratha.",
    image: "./nonvegstarters/6.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 7,
    name: "Crispy Chilli Chicken",
    price: 290,
    description: "Crispy fried chicken tossed in spicy Chinese-style chili sauce.",
    image: "./nonvegstarters/7.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 8,
    name: "Chicken Malai Tikka",
    price: 310,
    description: "Soft chicken pieces marinated in creamy, mild spices and grilled.",
    image: "./nonvegstarters/8.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 9,
    name: "Peri Peri Wings",
    price: 270,
    description: "Juicy chicken wings coated with spicy Peri Peri sauce.",
    image: "./nonvegstarters/9.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 10,
    name: "Egg Devil",
    price: 260,
    description: "Stuffed boiled eggs coated in breadcrumbs and deep-fried.",
    image: "./nonvegstarters/10.jpeg",
    button: true,
    quantity: 1,
  },
  {
    id: 11,
    name: "BBQ Chicken Wings",
    price: 290,
    description: "Smoky barbecue-flavored chicken wings, grilled to perfection.",
    image: "./nonvegstarters/11.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 12,
    name: "Garlic Butter Prawns",
    price: 400,
    description: "Juicy prawns cooked in garlic butter sauce with herbs.",
    image: "./nonvegstarters/12.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 13,
    name: "Mutton Shami Kebab",
    price: 360,
    description: "Minced mutton kebabs, shallow fried with authentic Indian spices.",
    image: "./nonvegstarters/13.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 14,
    name: "Fish Fingers",
    price: 300,
    description: "Crispy golden-fried fish fillets served with tartar sauce.",
    image: "./nonvegstarters/14.jpeg",
    button: true,
    quantity: 1,
  },
  {
    id: 15,
    name: "Egg Chilli Dry",
    price: 250,
    description: "Spicy stir-fried egg pieces tossed in Chinese chili sauce.",
    image: "./nonvegstarters/15.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 16,
    name: "Lemon Herb Grilled Chicken",
    price: 350,
    description: "Juicy grilled chicken infused with lemon and aromatic herbs.",
    image: "./nonvegstarters/16.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 17,
    name: "Tandoori Prawns",
    price: 420,
    description: "Prawns marinated in tandoori masala and grilled to perfection.",
    image: "./nonvegstarters/17.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 18,
    name: "Chili Garlic Fish",
    price: 310,
    description: "Fish fillets tossed in a spicy chili garlic sauce.",
    image: "./nonvegstarters/18.jpeg",
    button: true,
    quantity: 1,
  },
  {
    id: 19,
    name: "Mutton Pepper Fry",
    price: 380,
    description: "Spicy and peppery South Indian-style stir-fried mutton.",
    image: "./nonvegstarters/19.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 20,
    name: "Butter Garlic Crab",
    price: 450,
    description: "Fresh crab cooked in a flavorful butter garlic sauce.",
    image: "./nonvegstarters/20.jpg",
    button: true,
    quantity: 1,
  }
];

export default nonVegStarters;