const rotis = [
    {
      id: 1,
      name: "Tandoori Roti",
      price: 40,
      description: "Traditional whole wheat roti cooked in a tandoor.",
      image: "./rotis/1.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 2,
      name: "Butter Naan",
      price: 60,
      description: "Soft and fluffy naan brushed with butter.",
      image: "./rotis/2.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 3,
      name: "Garlic Naan",
      price: 70,
      description: "Naan infused with garlic and topped with fresh coriander.",
      image: "./rotis/3.jpeg",
      button: true,
      quantity: 1,
    },
    {
      id: 4,
      name: "Plain Roti",
      price: 30,
      description: "Simple whole wheat roti cooked on a tava.",
      image: "./rotis/4.jpeg",
      button: true,
      quantity: 1,
    },
    {
      id: 5,
      name: "Missi Roti",
      price: 50,
      description: "Rajasthani-style roti made from gram flour and wheat flour.",
      image: "./rotis/5.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 6,
      name: "Lachha Paratha",
      price: 70,
      description: "Multi-layered crispy paratha cooked with ghee.",
      image: "./rotis/6.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 7,
      name: "Stuffed Kulcha",
      price: 90,
      description: "Soft kulcha stuffed with spiced potatoes and herbs.",
      image: "./rotis/7.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 8,
      name: "Roomali Roti",
      price: 60,
      description: "Ultra-thin and soft roti folded like a handkerchief.",
      image: "./rotis/8.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 9,
      name: "Aloo Paratha",
      price: 80,
      description: "North Indian-style paratha stuffed with spiced mashed potatoes.",
      image: "./rotis/9.jpeg",
      button: true,
      quantity: 1,
    },
    {
      id: 10,
      name: "Cheese Naan",
      price: 100,
      description: "Soft naan stuffed with melted cheese and herbs.",
      image: "./rotis/10.jpeg",
      button: true,
      quantity: 1,
    },
    {
      id: 11,
      name: "Pudina Paratha",
      price: 75,
      description: "Flaky layered paratha flavored with mint and butter.",
      image: "./rotis/11.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 12,
      name: "Bajra Roti",
      price: 55,
      description: "Traditional millet flour roti, served with ghee.",
      image: "./rotis/12.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 13,
      name: "Methi Paratha",
      price: 70,
      description: "Paratha made with fresh fenugreek leaves and mild spices.",
      image: "./rotis/13.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 14,
      name: "Tawa Paratha",
      price: 65,
      description: "Crispy paratha cooked on a tava with a generous amount of ghee.",
      image: "./rotis/14.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 15,
      name: "Makki Ki Roti",
      price: 60,
      description: "Cornmeal flatbread, best served with sarson ka saag.",
      image: "./rotis/15.jpg",
      button: true,
      quantity: 1,
    }
  ];
  
  export default rotis;
  