const vegMainCourse = [
    {
      id: 1,
      name: "Paneer Butter Masala",
      price: 350,
      description: "Rich and creamy tomato-based gravy with soft paneer cubes.",
      image: "./VegMainCourse/1.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 2,
      name: "Dal Makhani",
      price: 320,
      description: "Slow-cooked black lentils with butter and cream, served with naan.",
      image: "./VegMainCourse/2.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 3,
      name: "Shahi Paneer",
      price: 360,
      description: "Paneer cooked in a creamy, mildly spiced cashew-based gravy.",
      image: "./VegMainCourse/3.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 4,
      name: "Veg Kolhapuri",
      price: 300,
      description: "Spicy and flavorful Maharashtrian mixed vegetable curry.",
      image: "./VegMainCourse/4.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 5,
      name: "Baingan Bharta",
      price: 280,
      description: "Smoky mashed brinjal cooked with onions, tomatoes, and spices.",
      image: "./VegMainCourse/5.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 6,
      name: "Chole Masala",
      price: 290,
      description: "Spicy and tangy chickpea curry, served best with bhature.",
      image: "./VegMainCourse/6.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 7,
      name: "Palak Paneer",
      price: 340,
      description: "Paneer cubes cooked in a smooth spinach-based gravy.",
      image: "./VegMainCourse/7.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 8,
      name: "Kadai Paneer",
      price: 350,
      description: "Paneer stir-fried with capsicum and spices in a thick tomato gravy.",
      image: "./VegMainCourse/8.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 9,
      name: "Methi Malai Matar",
      price: 310,
      description: "Creamy fenugreek and green peas curry with a mild spice flavor.",
      image: "./VegMainCourse/9.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 10,
      name: "Aloo Gobhi",
      price: 270,
      description: "Stir-fried cauliflower and potatoes cooked with Indian spices.",
      image: "./VegMainCourse/10.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 11,
      name: "Rajma Masala",
      price: 300,
      description: "Red kidney beans cooked in a rich tomato-based gravy.",
      image: "./VegMainCourse/11.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 12,
      name: "Bhindi Masala",
      price: 280,
      description: "Stir-fried okra with onions, tomatoes, and Indian spices.",
      image: "./VegMainCourse/12.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 13,
      name: "Mix Veg Curry",
      price: 310,
      description: "A mix of seasonal vegetables cooked in a flavorful masala gravy.",
      image: "./VegMainCourse/13.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 14,
      name: "Malai Kofta",
      price: 360,
      description: "Paneer and potato balls cooked in a rich, creamy gravy.",
      image: "./VegMainCourse/14.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 15,
      name: "Jeera Aloo",
      price: 260,
      description: "Simple and tasty cumin-flavored potato dish.",
      image: "./VegMainCourse/15.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 16,
      name: "Dum Aloo",
      price: 310,
      description: "Baby potatoes cooked in a rich and spicy yogurt-based gravy.",
      image: "./VegMainCourse/16.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 17,
      name: "Paneer Lababdar",
      price: 370,
      description: "Paneer cooked in a spicy, creamy tomato-based gravy with rich flavors.",
      image: "./VegMainCourse/17.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 18,
      name: "Mushroom Masala",
      price: 330,
      description: "Mushrooms cooked in a thick onion and tomato gravy with spices.",
      image: "./VegMainCourse/18.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 19,
      name: "Gatte Ki Sabzi",
      price: 290,
      description: "Traditional Rajasthani dish with gram flour dumplings in yogurt gravy.",
      image: "./VegMainCourse/19.jpg",
      button: true,
      quantity: 1,
    },
    {
      id: 20,
      name: "Paneer Bhurji",
      price: 320,
      description: "Scrambled paneer cooked with onions, tomatoes, and Indian spices.",
      image: "./VegMainCourse/20.jpg",
      button: true,
      quantity: 1,
    }
  ];
  
  export default vegMainCourse;
  