const vegStarters = [{
    id: 1,
    name: "Paneer Tikka",
    price: 250,
    description: "Grilled paneer cubes marinated in a blend of spices and yogurt.",
    image: "./VegStartersImg/1.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 2,
    name: "Crispy Corn",
    price: 180,
    description: "Crispy fried corn tossed with onions, chilies, and chat masala.",
    image: "./VegStartersImg/2.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 3,
    name: "Hara Bhara Kebab",
    price: 220,
    description: "Healthy and delicious spinach and green pea kebabs served with mint chutney.",
    image: "./VegStartersImg/3.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 4,
    name: "Stuffed Mushroom",
    price: 260,
    description: "Juicy mushrooms stuffed with cheese, herbs, and spices, then grilled to perfection.",
    image: "./VegStartersImg/4.jpg",

    button: true,
    quantity: 1,
  },
  {
    id: 5,
    name: "Dahi Ke Kebab",
    price: 240,
    description: "Delicate hung curd kebabs infused with spices, deep-fried to perfection.",
    image: "./VegStartersImg/5.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 6,
    name: "Chilli Paneer",
    price: 270,
    description: "Crispy paneer tossed in a spicy and tangy Chinese-style chili sauce.",
    image: "./VegStartersImg/6.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 7,
    name: "Spring Rolls",
    price: 190,
    description: "Crispy fried rolls stuffed with a mix of fresh vegetables and glass noodles.",
    image: "./VegStartersImg/7.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 8,
    name: "Veg Seekh Kebab",
    price: 230,
    description: "Minced vegetable kebabs infused with aromatic spices, grilled to perfection.",
    image: "./VegStartersImg/8.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 9,
    name: "Honey Chilli Potato",
    price: 200,
    description: "Crispy fried potato fingers tossed in honey and chili sauce with sesame seeds.",
    image: "./VegStartersImg/9.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 10,
    name: "Tandoori Broccoli",
    price: 280,
    description: "Broccoli florets marinated in yogurt and Indian spices, cooked in a tandoor.",
    image: "./VegStartersImg/10.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 11,
    name: "Peri Peri Fries",
    price: 150,
    description: "Crispy French fries coated with spicy Peri Peri seasoning.",
    image: "./VegStartersImg/11.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 12,
    name: "Masala Papad",
    price: 100,
    description: "Crispy papad topped with tangy onions, tomatoes, and spicy masala.",
    image: "./VegStartersImg/12.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 13,
    name: "Cheese Garlic Bread",
    price: 180,
    description: "Crispy bread topped with melted cheese and garlic butter.",
    image: "./VegStartersImg/13.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 14,
    name: "Corn Cheese Balls",
    price: 220,
    description: "Crispy deep-fried balls filled with gooey cheese and sweet corn.",
    image: "./VegStartersImg/14.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 15,
    name: "Rajma Galouti Kebab",
    price: 260,
    description: "Mouth-melting kebabs made with rajma and aromatic Indian spices.",
    image: "./VegStartersImg/15.webp",
    button: true,
    quantity: 1,
  },
  {
    id: 16,
    name: "Aloo Tikki",
    price: 140,
    description: "Crispy mashed potato patties served with mint and tamarind chutney.",
    image: "./VegStartersImg/16.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 17,
    name: "Veg Manchurian",
    price: 270,
    description: "Deep-fried vegetable balls tossed in a spicy Chinese sauce.",
    image: "./VegStartersImg/17.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 18,
    name: "Malai Chaap",
    price: 280,
    description: "Soft soya chaap cooked in a creamy, flavorful marinade.",
    image: "./VegStartersImg/18.webp",
    button: true,
    quantity: 1,
  },
  {
    id: 19,
    name: "Kurkure Momos",
    price: 250,
    description: "Crispy fried momos coated with a crunchy outer layer.",
    image: "./VegStartersImg/19.jpg",
    button: true,
    quantity: 1,
  },
  {
    id: 20,
    name: "Cheese Chilli Toast",
    price: 210,
    description: "Spicy and cheesy toast topped with green chilies and herbs.",
    image: "./VegStartersImg/20.jpg",
    button: true,
    quantity: 1,
  }
];

export default vegStarters;